# 監聽 1883 埠，並允許外部 IP 連線
listener 1883 0.0.0.0

# 測試階段先允許匿名連線（免帳密），之後要加密碼再改為 false
allow_anonymous true


connection bridge-to-remote
address iot.eastsoft.com.cn:1883
# 禁用預設的狀態主題發布，避免觸發遠端 ACL
notifications false

# 2. 避免 ClientID 衝突 (使用最獨特的 ID)
clientid VEGA_BRIDGE_260720

# 確保遠端 Broker 不會保留舊的訂閱狀態
cleansession true

# 4. 遠端broker認證 
remote_username 938aee00-1ecf-42aa-bed1-1e7f1ac186a2
remote_password XxH63DrF



# 1. 輸出：把本地 eastsoft/+/+ 發布的訊息，去掉 eastsoft/ 改加上 2IWVCE1MW/ 送到遠端
topic +/+ out 1 eastsoft/ 2IX50P8XW/

# 2. 輸入：把遠端 2IWVCE1MW/+/+/command 的訊息訂閱下來，在本地改以 eastsoft/+/+/command 接收
topic +/+/command in 1 eastsoft/ 2IX50P8XW/


# 嘗試私有會話 (當 Bridge 連線斷開時，遠端 Broker 不會刪除訂閱)
try_private false

notifications false

# 自動重連類型
start_type automatic